#Nightfall Tactics Settings
#Mon Mar 09 01:45:13 GMT+08:00 2026
AUDIO_ENABLED=true
BACK=27
MASTER_VOLUME=85
MUSIC_VOLUME=55
P1_BLOCK=66
P1_CROUCH=83
P1_HEAVY=71
P1_JUMP=87
P1_KICK=86
P1_LEFT=65
P1_LIGHT=70
P1_RIGHT=68
P1_SPECIAL=82
P1_ULT=84
P2_BLOCK=77
P2_CROUCH=40
P2_HEAVY=75
P2_JUMP=38
P2_KICK=78
P2_LEFT=37
P2_LIGHT=74
P2_RIGHT=39
P2_SPECIAL=79
P2_ULT=80
PAUSE=32
SFX_VOLUME=90
